apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: "Laravel K8s"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  LOG_CHANNEL: "stack"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "laravel_db"
  DB_USERNAME: "user"